/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Entidades.Funcionario.view;

import java.awt.Label;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp elitebook
 */
public class Cadrastro_de_F extends javax.swing.JFrame {

    /**
     * Creates new form Cadrastro_de_Funcionario
     */
    public Cadrastro_de_F() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        txtNacionalidade13 = new javax.swing.JTextField();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        txtEstadoCivil13 = new javax.swing.JComboBox<>();
        txtProfissao13 = new javax.swing.JTextField();
        txtGenero13 = new javax.swing.JComboBox<>();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        CadastrarPaciente13 = new javax.swing.JToggleButton();
        txtTelefoneLabel13 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        txtNascimento13 = new javax.swing.JFormattedTextField();
        txtTel27 = new javax.swing.JFormattedTextField();
        txtTel28 = new javax.swing.JFormattedTextField();
        txtAltura13 = new javax.swing.JFormattedTextField();
        txtPeso13 = new javax.swing.JFormattedTextField();
        txtNome13 = new javax.swing.JFormattedTextField();
        txtEmail13 = new javax.swing.JFormattedTextField();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        txtBI13 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel19.setBackground(new java.awt.Color(153, 0, 51));

        jPanel18.setBackground(new java.awt.Color(153, 0, 51));

        jLabel183.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel183.setForeground(new java.awt.Color(255, 255, 255));
        jLabel183.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel183.setText(" Cadastro do Funcionário");

        jLabel184.setText("Nome Completo*");

        jLabel185.setText("Profissão");

        jLabel187.setText("BI*");

        jLabel188.setText("Nacionalidade");

        jLabel189.setText("Altura");

        jLabel190.setText("Peso");

        jLabel191.setText("Estado Cívil");

        txtEstadoCivil13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", " " }));

        txtGenero13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel192.setText("Genero");

        jLabel193.setText("Nascimento(AA-MM-DD)");

        CadastrarPaciente13.setBackground(new java.awt.Color(0, 0, 0));
        CadastrarPaciente13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CadastrarPaciente13.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarPaciente13.setText("Cadastrar");
        CadastrarPaciente13.setBorderPainted(false);
        CadastrarPaciente13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarPacienteActionPerformed(evt);
            }
        });

        txtTelefoneLabel13.setText("Tel.");

        jLabel194.setText("Tel.(opcional)");

        try {
            txtNascimento13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTel27.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+244) 9## ### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTel28.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+244) 9## ### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtAltura13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltura13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });

        try {
            txtPeso13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##0")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtEmail13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel195.setText("Email");

        jLabel196.setBackground(new java.awt.Color(0, 0, 0));
        jLabel196.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp elitebook\\Pictures\\Imagens\\imagens do projeto clinica girasso\\Login2-removebg valido.png")); // NOI18N

        try {
            txtBI13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBI13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBI13, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome13, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel196))
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel18Layout.createSequentialGroup()
                                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtNascimento13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel193, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(61, 61, 61)
                                            .addComponent(txtEstadoCivil13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel18Layout.createSequentialGroup()
                                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPeso13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel189))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel190)
                                                .addGroup(jPanel18Layout.createSequentialGroup()
                                                    .addComponent(txtAltura13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtGenero13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel188)
                                    .addComponent(jLabel185)
                                    .addComponent(jLabel187, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel184)
                                    .addComponent(txtNacionalidade13, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(txtProfissao13))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel18Layout.createSequentialGroup()
                                                .addComponent(txtEmail13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel186))
                                            .addComponent(txtTelefoneLabel13)
                                            .addComponent(txtTel27, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel191)
                                            .addComponent(jLabel194)
                                            .addComponent(jLabel192)
                                            .addComponent(txtTel28, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel195, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel183)
                            .addComponent(CadastrarPaciente13, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(195, 195, 195))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel196)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel183)
                .addGap(10, 10, 10)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel190, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel184, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel189, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel192, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNome13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel193)
                            .addComponent(jLabel187)
                            .addComponent(jLabel191))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNascimento13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoCivil13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBI13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel188)
                            .addComponent(txtTelefoneLabel13)
                            .addComponent(jLabel194))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNacionalidade13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPeso13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAltura13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGenero13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel185)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfissao13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel195)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel186))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24)
                .addComponent(CadastrarPaciente13)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Anterior", jPanel19);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBIActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void CadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadrastro_de_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadrastro_de_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadrastro_de_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadrastro_de_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadrastro_de_F().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CadastrarPaciente;
    private javax.swing.JToggleButton CadastrarPaciente1;
    private javax.swing.JToggleButton CadastrarPaciente10;
    private javax.swing.JToggleButton CadastrarPaciente11;
    private javax.swing.JToggleButton CadastrarPaciente12;
    private javax.swing.JToggleButton CadastrarPaciente13;
    private javax.swing.JToggleButton CadastrarPaciente2;
    private javax.swing.JToggleButton CadastrarPaciente3;
    private javax.swing.JToggleButton CadastrarPaciente4;
    private javax.swing.JToggleButton CadastrarPaciente5;
    private javax.swing.JToggleButton CadastrarPaciente6;
    private javax.swing.JToggleButton CadastrarPaciente7;
    private javax.swing.JToggleButton CadastrarPaciente8;
    private javax.swing.JToggleButton CadastrarPaciente9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField txtAltura;
    private javax.swing.JFormattedTextField txtAltura1;
    private javax.swing.JFormattedTextField txtAltura10;
    private javax.swing.JFormattedTextField txtAltura11;
    private javax.swing.JFormattedTextField txtAltura12;
    private javax.swing.JFormattedTextField txtAltura13;
    private javax.swing.JFormattedTextField txtAltura2;
    private javax.swing.JFormattedTextField txtAltura3;
    private javax.swing.JFormattedTextField txtAltura4;
    private javax.swing.JFormattedTextField txtAltura5;
    private javax.swing.JFormattedTextField txtAltura6;
    private javax.swing.JFormattedTextField txtAltura7;
    private javax.swing.JFormattedTextField txtAltura8;
    private javax.swing.JFormattedTextField txtAltura9;
    private javax.swing.JFormattedTextField txtBI;
    private javax.swing.JFormattedTextField txtBI1;
    private javax.swing.JFormattedTextField txtBI10;
    private javax.swing.JFormattedTextField txtBI11;
    private javax.swing.JFormattedTextField txtBI12;
    private javax.swing.JFormattedTextField txtBI13;
    private javax.swing.JFormattedTextField txtBI2;
    private javax.swing.JFormattedTextField txtBI3;
    private javax.swing.JFormattedTextField txtBI4;
    private javax.swing.JFormattedTextField txtBI5;
    private javax.swing.JFormattedTextField txtBI6;
    private javax.swing.JFormattedTextField txtBI7;
    private javax.swing.JFormattedTextField txtBI8;
    private javax.swing.JFormattedTextField txtBI9;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtEmail1;
    private javax.swing.JFormattedTextField txtEmail10;
    private javax.swing.JFormattedTextField txtEmail11;
    private javax.swing.JFormattedTextField txtEmail12;
    private javax.swing.JFormattedTextField txtEmail13;
    private javax.swing.JFormattedTextField txtEmail2;
    private javax.swing.JFormattedTextField txtEmail3;
    private javax.swing.JFormattedTextField txtEmail4;
    private javax.swing.JFormattedTextField txtEmail5;
    private javax.swing.JFormattedTextField txtEmail6;
    private javax.swing.JFormattedTextField txtEmail7;
    private javax.swing.JFormattedTextField txtEmail8;
    private javax.swing.JFormattedTextField txtEmail9;
    private javax.swing.JComboBox<String> txtEstadoCivil;
    private javax.swing.JComboBox<String> txtEstadoCivil1;
    private javax.swing.JComboBox<String> txtEstadoCivil10;
    private javax.swing.JComboBox<String> txtEstadoCivil11;
    private javax.swing.JComboBox<String> txtEstadoCivil12;
    private javax.swing.JComboBox<String> txtEstadoCivil13;
    private javax.swing.JComboBox<String> txtEstadoCivil2;
    private javax.swing.JComboBox<String> txtEstadoCivil3;
    private javax.swing.JComboBox<String> txtEstadoCivil4;
    private javax.swing.JComboBox<String> txtEstadoCivil5;
    private javax.swing.JComboBox<String> txtEstadoCivil6;
    private javax.swing.JComboBox<String> txtEstadoCivil7;
    private javax.swing.JComboBox<String> txtEstadoCivil8;
    private javax.swing.JComboBox<String> txtEstadoCivil9;
    private javax.swing.JComboBox<String> txtGenero;
    private javax.swing.JComboBox<String> txtGenero1;
    private javax.swing.JComboBox<String> txtGenero10;
    private javax.swing.JComboBox<String> txtGenero11;
    private javax.swing.JComboBox<String> txtGenero12;
    private javax.swing.JComboBox<String> txtGenero13;
    private javax.swing.JComboBox<String> txtGenero2;
    private javax.swing.JComboBox<String> txtGenero3;
    private javax.swing.JComboBox<String> txtGenero4;
    private javax.swing.JComboBox<String> txtGenero5;
    private javax.swing.JComboBox<String> txtGenero6;
    private javax.swing.JComboBox<String> txtGenero7;
    private javax.swing.JComboBox<String> txtGenero8;
    private javax.swing.JComboBox<String> txtGenero9;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNacionalidade1;
    private javax.swing.JTextField txtNacionalidade10;
    private javax.swing.JTextField txtNacionalidade11;
    private javax.swing.JTextField txtNacionalidade12;
    private javax.swing.JTextField txtNacionalidade13;
    private javax.swing.JTextField txtNacionalidade2;
    private javax.swing.JTextField txtNacionalidade3;
    private javax.swing.JTextField txtNacionalidade4;
    private javax.swing.JTextField txtNacionalidade5;
    private javax.swing.JTextField txtNacionalidade6;
    private javax.swing.JTextField txtNacionalidade7;
    private javax.swing.JTextField txtNacionalidade8;
    private javax.swing.JTextField txtNacionalidade9;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JFormattedTextField txtNascimento1;
    private javax.swing.JFormattedTextField txtNascimento10;
    private javax.swing.JFormattedTextField txtNascimento11;
    private javax.swing.JFormattedTextField txtNascimento12;
    private javax.swing.JFormattedTextField txtNascimento13;
    private javax.swing.JFormattedTextField txtNascimento2;
    private javax.swing.JFormattedTextField txtNascimento3;
    private javax.swing.JFormattedTextField txtNascimento4;
    private javax.swing.JFormattedTextField txtNascimento5;
    private javax.swing.JFormattedTextField txtNascimento6;
    private javax.swing.JFormattedTextField txtNascimento7;
    private javax.swing.JFormattedTextField txtNascimento8;
    private javax.swing.JFormattedTextField txtNascimento9;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JFormattedTextField txtNome1;
    private javax.swing.JFormattedTextField txtNome10;
    private javax.swing.JFormattedTextField txtNome11;
    private javax.swing.JFormattedTextField txtNome12;
    private javax.swing.JFormattedTextField txtNome13;
    private javax.swing.JFormattedTextField txtNome2;
    private javax.swing.JFormattedTextField txtNome3;
    private javax.swing.JFormattedTextField txtNome4;
    private javax.swing.JFormattedTextField txtNome5;
    private javax.swing.JFormattedTextField txtNome6;
    private javax.swing.JFormattedTextField txtNome7;
    private javax.swing.JFormattedTextField txtNome8;
    private javax.swing.JFormattedTextField txtNome9;
    private javax.swing.JFormattedTextField txtPeso;
    private javax.swing.JFormattedTextField txtPeso1;
    private javax.swing.JFormattedTextField txtPeso10;
    private javax.swing.JFormattedTextField txtPeso11;
    private javax.swing.JFormattedTextField txtPeso12;
    private javax.swing.JFormattedTextField txtPeso13;
    private javax.swing.JFormattedTextField txtPeso2;
    private javax.swing.JFormattedTextField txtPeso3;
    private javax.swing.JFormattedTextField txtPeso4;
    private javax.swing.JFormattedTextField txtPeso5;
    private javax.swing.JFormattedTextField txtPeso6;
    private javax.swing.JFormattedTextField txtPeso7;
    private javax.swing.JFormattedTextField txtPeso8;
    private javax.swing.JFormattedTextField txtPeso9;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JTextField txtProfissao1;
    private javax.swing.JTextField txtProfissao10;
    private javax.swing.JTextField txtProfissao11;
    private javax.swing.JTextField txtProfissao12;
    private javax.swing.JTextField txtProfissao13;
    private javax.swing.JTextField txtProfissao2;
    private javax.swing.JTextField txtProfissao3;
    private javax.swing.JTextField txtProfissao4;
    private javax.swing.JTextField txtProfissao5;
    private javax.swing.JTextField txtProfissao6;
    private javax.swing.JTextField txtProfissao7;
    private javax.swing.JTextField txtProfissao8;
    private javax.swing.JTextField txtProfissao9;
    private javax.swing.JFormattedTextField txtTel1;
    private javax.swing.JFormattedTextField txtTel10;
    private javax.swing.JFormattedTextField txtTel11;
    private javax.swing.JFormattedTextField txtTel12;
    private javax.swing.JFormattedTextField txtTel13;
    private javax.swing.JFormattedTextField txtTel14;
    private javax.swing.JFormattedTextField txtTel15;
    private javax.swing.JFormattedTextField txtTel16;
    private javax.swing.JFormattedTextField txtTel17;
    private javax.swing.JFormattedTextField txtTel18;
    private javax.swing.JFormattedTextField txtTel19;
    private javax.swing.JFormattedTextField txtTel2;
    private javax.swing.JFormattedTextField txtTel20;
    private javax.swing.JFormattedTextField txtTel21;
    private javax.swing.JFormattedTextField txtTel22;
    private javax.swing.JFormattedTextField txtTel23;
    private javax.swing.JFormattedTextField txtTel24;
    private javax.swing.JFormattedTextField txtTel25;
    private javax.swing.JFormattedTextField txtTel26;
    private javax.swing.JFormattedTextField txtTel27;
    private javax.swing.JFormattedTextField txtTel28;
    private javax.swing.JFormattedTextField txtTel3;
    private javax.swing.JFormattedTextField txtTel4;
    private javax.swing.JFormattedTextField txtTel5;
    private javax.swing.JFormattedTextField txtTel6;
    private javax.swing.JFormattedTextField txtTel7;
    private javax.swing.JFormattedTextField txtTel8;
    private javax.swing.JFormattedTextField txtTel9;
    private javax.swing.JLabel txtTelefoneLabel;
    private javax.swing.JLabel txtTelefoneLabel1;
    private javax.swing.JLabel txtTelefoneLabel10;
    private javax.swing.JLabel txtTelefoneLabel11;
    private javax.swing.JLabel txtTelefoneLabel12;
    private javax.swing.JLabel txtTelefoneLabel13;
    private javax.swing.JLabel txtTelefoneLabel2;
    private javax.swing.JLabel txtTelefoneLabel3;
    private javax.swing.JLabel txtTelefoneLabel4;
    private javax.swing.JLabel txtTelefoneLabel5;
    private javax.swing.JLabel txtTelefoneLabel6;
    private javax.swing.JLabel txtTelefoneLabel7;
    private javax.swing.JLabel txtTelefoneLabel8;
    private javax.swing.JLabel txtTelefoneLabel9;
    // End of variables declaration//GEN-END:variables


private void CadastraFuncionarioEvent(){


}
}
